[build]
  command = "npm install --production"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/process-pdf"
  to = "/.netlify/functions/process-pdf"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200