[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/process-pdf"
  to = "/.netlify/functions/process-pdf"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200